"""
Base Strategy Classes for Trading Strategies

This module provides the abstract base class for all trading strategies,
along with supporting data structures for trade signals and configuration.
"""






from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Tuple
from enum import Enum
import pandas as pd
import numpy as np


class SignalType(Enum):
    """Trading signal types"""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class TradeSignal:
    """
    Represents a trading signal generated by a strategy.

    Attributes:
        action: The trading action (BUY, SELL, HOLD)
        confidence: Confidence level 0.0 to 1.0
        price: Current price when signal was generated
        timestamp: Time of the signal
        indicator_values: Dict of indicator values that triggered the signal
        metadata: Additional strategy-specific metadata
    """
    action: str
    confidence: float
    price: float
    timestamp: pd.Timestamp = None
    indicator_values: Dict[str, float] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate signal after initialization"""
        if self.action not in ['BUY', 'SELL', 'HOLD']:
            raise ValueError(f"Invalid action: {self.action}. Must be BUY, SELL, or HOLD")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be between 0.0 and 1.0, got {self.confidence}")

    @property
    def is_entry(self) -> bool:
        """Returns True if this is an entry signal (BUY)"""
        return self.action == 'BUY'

    @property
    def is_exit(self) -> bool:
        """Returns True if this is an exit signal (SELL)"""
        return self.action == 'SELL'

    def to_dict(self) -> Dict:
        """Convert signal to dictionary"""
        return {
            'action': self.action,
            'confidence': self.confidence,
            'price': self.price,
            'timestamp': str(self.timestamp) if self.timestamp else None,
            'indicator_values': self.indicator_values,
            'metadata': self.metadata
        }


@dataclass
class StrategyConfig:
    """
    Configuration for a trading strategy.

    Attributes:
        name: Strategy name
        params: Strategy-specific parameters
        position_size: Fraction of capital to use per trade (0.0 to 1.0)
        min_confidence: Minimum confidence threshold to act on signal
        cooldown_periods: Minimum periods between trades
    """
    name: str
    params: Dict[str, Any] = field(default_factory=dict)
    position_size: float = 0.95  # Use 95% of capital
    min_confidence: float = 0.5
    cooldown_periods: int = 1

    def __post_init__(self):
        if not 0.0 < self.position_size <= 1.0:
            raise ValueError(f"position_size must be between 0 and 1, got {self.position_size}")
        if not 0.0 <= self.min_confidence <= 1.0:
            raise ValueError(f"min_confidence must be between 0 and 1, got {self.min_confidence}")


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategies must implement:
    - name: Unique strategy identifier
    - description: Human-readable description
    - generate_signals(): Generate trading signals from data
    - get_required_features(): List required DataFrame columns

    Example usage:
        class MyStrategy(BaseStrategy):
            @property
            def name(self) -> str:
                return "my_strategy"

            def generate_signals(self, data: pd.DataFrame) -> List[TradeSignal]:
                # Your signal logic here
                pass
    """

    def __init__(self, config: Optional[StrategyConfig] = None):
        """
        Initialize the strategy.

        Args:
            config: Strategy configuration. If None, uses defaults.
        """
        self.config = config or StrategyConfig(name=self.name, params=self.get_default_params())
        self._validate_params()

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique strategy identifier"""
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """Human-readable description of the strategy"""
        pass

    @abstractmethod
    def generate_signals(self, data: pd.DataFrame) -> List[TradeSignal]:
        """
        Generate trading signals from market data.

        Args:
            data: DataFrame with OHLCV and technical indicators

        Returns:
            List of TradeSignal objects, one per row in data
        """
        pass

    @abstractmethod
    def get_required_features(self) -> List[str]:
        """
        Get list of required DataFrame columns.

        Returns:
            List of column names this strategy needs
        """
        pass

    def get_default_params(self) -> Dict[str, Any]:
        """
        Return default parameters for this strategy.
        Override in subclasses to provide strategy-specific defaults.
        """
        return {}

    def _validate_params(self):
        """
        Validate strategy parameters.
        Override in subclasses to add custom validation.
        """
        pass

    def validate_data(self, data: pd.DataFrame) -> Tuple[bool, List[str]]:
        """
        Check if data has all required features.

        Args:
            data: DataFrame to validate

        Returns:
            Tuple of (is_valid, missing_features)
        """
        required = set(self.get_required_features())
        available = set(data.columns)
        missing = required - available
        return len(missing) == 0, list(missing)

    def get_indicator_value(self, row: pd.Series, feature: str, default: float = 0.0) -> float:
        """
        Safely get indicator value from a row.

        Args:
            row: Data row
            feature: Feature name
            default: Default value if feature not found or NaN

        Returns:
            Feature value or default
        """
        value = row.get(feature, default)
        if pd.isna(value):
            return default
        return float(value)

    def calculate_confidence(self, value: float, threshold: float,
                            scale: float = 1.0, invert: bool = False) -> float:
        """
        Calculate confidence score based on how far value is from threshold.

        Args:
            value: Current indicator value
            threshold: Threshold that triggered the signal
            scale: Scaling factor for confidence calculation
            invert: If True, higher values mean lower confidence

        Returns:
            Confidence score between 0.0 and 1.0
        """
        diff = abs(value - threshold)
        confidence = min(diff * scale, 1.0)
        if invert:
            confidence = 1.0 - confidence
        return max(0.0, min(1.0, confidence))

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self.name}', params={self.config.params})"
